#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../" && pwd)"
cd "$REPO_ROOT"

ARCH="$(uname -m)"

VERSION="$(
	python3 - <<'PY'
import re, pathlib
p = pathlib.Path("src/__init__.py").read_text(encoding="utf-8")
m = re.search(r'__version__\s*=\s*"([^"]+)"', p)
print(m.group(1) if m else "0.0.0")
PY
)"

# Allow tags like:
#   vX.Y.Z
#   vX.Y.Z-beta
#   vX.Y.Z-beta.3
#   vX.Y.Z-alpha(.N) / vX.Y(.Z)-dev(.N)
TAG_CANDIDATE="${TAG_OVERRIDE:-${GITHUB_REF_NAME:-${GIT_TAG:-}}}"
if [[ -n "${TAG_CANDIDATE}" && "${TAG_CANDIDATE}" =~ ^v([0-9]+(\.[0-9]+){1,2})(-(dev|alpha|beta)(\.[0-9]+)?)?$ ]]; then
	VERSION="${BASH_REMATCH[1]}"
	if [[ -z "${PREID:-}" ]]; then
		PREID="${BASH_REMATCH[4]:-}${BASH_REMATCH[5]:-}"  # e.g. "beta" or "beta.2"
	fi
fi

BRANCH="${BRANCH_OVERRIDE:-${GITHUB_REF_NAME:-${CI_COMMIT_BRANCH:-${BUILDKITE_BRANCH:-${CIRCLE_BRANCH:-${BITBUCKET_BRANCH:-$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")}}}}}}"
PREID="${PREID:-}"
if [[ -z "${PREID}" ]]; then
	case "${BRANCH}" in
		main|master) PREID="" ;;
		beta|beta/*|release/beta|release/*beta*) PREID="beta" ;;
		alpha|alpha/*|release/alpha|release/*alpha*) PREID="alpha" ;;
		dev|develop|development|dev/*|feature/*|bugfix/*) PREID="dev" ;;
		""|*) PREID="dev" ;;
	esac
fi

# Validate PREID: allow bare channel or channel with numeric suffix, e.g. beta.7
if [[ -n "${PREID}" ]]; then
	if ! [[ "${PREID}" =~ ^(dev|alpha|beta)(\.[0-9]+)?$ ]]; then
		echo "error: PREID must be dev|alpha|beta (optionally with .N), or empty." >&2
		exit 2
	fi
fi

EFFECTIVE_VERSION="${VERSION}"; [[ -n "${PREID}" ]] && EFFECTIVE_VERSION="${VERSION}-${PREID}"

echo "Building whyx ${EFFECTIVE_VERSION} for ${ARCH} (branch=${BRANCH:-unknown}, tag=${TAG_CANDIDATE:-none}) …"

BUILD_META="${REPO_ROOT}/src/_build_meta.py"
cat > "${BUILD_META}" <<EOF
# Auto-generated by packaging/macos/build_binary.sh (do not commit)
EFFECTIVE_VERSION = "${EFFECTIVE_VERSION}"
BASE_VERSION = "${VERSION}"
CHANNEL = "${PREID}"
BRANCH = "${BRANCH:-}"
TAG = "${TAG_CANDIDATE:-}"
EOF
trap 'rm -f "${BUILD_META}"' EXIT

BUILD_VENV="${REPO_ROOT}/.packaging-venv"
if [[ ! -d "${BUILD_VENV}" ]]; then
	python3 -m venv "${BUILD_VENV}"
	"${BUILD_VENV}/bin/python" -m pip -q install --upgrade pip wheel setuptools
fi
"${BUILD_VENV}/bin/python" -m pip -q install pyinstaller

rm -rf build dist
mkdir -p build dist

if [[ -f "whyx.spec" ]]; then
	"${BUILD_VENV}/bin/pyinstaller" --clean -y whyx.spec
else
	# IMPORTANT: build from the package entry (src/main.py) so relative imports resolve when frozen
	"${BUILD_VENV}/bin/pyinstaller" \
		--clean \
		--onefile \
		--name "whyx" \
		--console \
		-p . \
		src/main.py
fi

OUT_DIR="build/artifacts"
mkdir -p "${OUT_DIR}"

BIN="dist/whyx"
chmod +x "${BIN}"

TARBALL="${OUT_DIR}/whyx_${EFFECTIVE_VERSION}_darwin_${ARCH}.tar.gz"
ZIPBALL="${OUT_DIR}/whyx_${EFFECTIVE_VERSION}_darwin_${ARCH}.zip"

tar -C dist -czf "${TARBALL}" "whyx"
zip -q -j "${ZIPBALL}" "${BIN}"

pushd "${OUT_DIR}" >/dev/null
BASE_TAR="$(basename "${TARBALL}")"
BASE_ZIP="$(basename "${ZIPBALL}")"
touch SHA256SUMS
tmpfile="$(mktemp SHA256SUMS.XXXXXX)"
grep -F -v -e "${BASE_TAR}" -e "${BASE_ZIP}" SHA256SUMS > "${tmpfile}" || true
shasum -a 256 "${BASE_TAR}" >> "${tmpfile}"
shasum -a 256 "${BASE_ZIP}" >> "${tmpfile}"
mv "${tmpfile}" SHA256SUMS
popd >/dev/null

echo
echo "✔ Binary:        ${BIN}"
echo "✔ Tarball:       ${TARBALL}"
echo "✔ Zip:           ${ZIPBALL}"
echo "✔ SHA256SUMS:    ${OUT_DIR}/SHA256SUMS"
echo
echo "Tag suggestion:  v${EFFECTIVE_VERSION}"
echo "Tip: upload artifacts + SHA256SUMS to a GitHub Release tagged v${EFFECTIVE_VERSION}."
